# Generated by Django 3.2.6 on 2021-09-09 05:07

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cpanel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, null=True, unique=True)),
                ('description', models.CharField(blank=True, max_length=150, null=True)),
                ('file', models.FileField(null=True, upload_to='files/mine/%Y/%m/%d')),
                ('is_published', models.BooleanField(default=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AdminList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=35, null=True, unique=True)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('price', models.CharField(max_length=30, null=True)),
                ('is_published', models.BooleanField(default=True, null=True)),
                ('related_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cpanel.adminfile')),
            ],
        ),
        migrations.CreateModel(
            name='StudentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_file', models.FileField(blank=True, null=True, upload_to='files/customers/%Y/%m/%d', validators=[django.core.validators.FileExtensionValidator(['pdf', 'docx', 'doc'])])),
                ('response_file', models.FileField(blank=True, null=True, upload_to='files/customers/%Y/%m/%d', validators=[django.core.validators.FileExtensionValidator(['pdf', 'docx', 'doc'])])),
                ('description', models.TextField(blank=True, null=True)),
                ('order_id', models.TextField(blank=True)),
                ('is_payed', models.BooleanField(default=False)),
                ('is_done', models.BooleanField(default=False, null=True)),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True)),
                ('title', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cpanel.adminlist')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
