# Generated by Django 3.2.6 on 2021-08-30 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Ali Baghban', max_length=35)),
                ('description', models.TextField()),
                ('photo', models.ImageField(upload_to='profile/%Y/%m/%d/')),
                ('phone', models.CharField(default='+989100366857', max_length=20)),
                ('instagram', models.CharField(default='alibaghban.ir', max_length=20)),
                ('telegram', models.CharField(default='alibaghban_ir', max_length=20)),
                ('whatsapp', models.CharField(default='+989100366857', max_length=20)),
                ('other', models.CharField(default='alibaghban.ir', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ExampleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(blank=True, max_length=150)),
                ('photo', models.ImageField(upload_to='application/%Y/%m/%d/')),
            ],
        ),
    ]
