# Generated by Django 3.2.6 on 2021-09-09 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Example',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, null=True)),
                ('caption', models.CharField(max_length=150, null=True)),
                ('photo', models.ImageField(null=True, upload_to='application/%Y/%m/%d/')),
                ('is_published', models.BooleanField(default=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.CharField(choices=[('Site Status', 'Site Status')], max_length=20, unique=True)),
                ('status', models.BooleanField(choices=[(True, 'Site Up'), (False, 'Site Down')], default=True, null=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='AboutModel',
            new_name='About',
        ),
        migrations.DeleteModel(
            name='ExampleModel',
        ),
    ]
