# Generated by Django 3.2.6 on 2021-08-30 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examplemodel',
            name='caption',
            field=models.CharField(max_length=150),
        ),
    ]
