# Generated by Django 3.2.6 on 2021-09-09 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210909_0937'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='phone',
        ),
        migrations.AddField(
            model_name='about',
            name='youtube',
            field=models.CharField(default='#', max_length=20),
        ),
        migrations.AlterField(
            model_name='about',
            name='instagram',
            field=models.CharField(default='sonopaniz', max_length=20),
        ),
        migrations.AlterField(
            model_name='about',
            name='telegram',
            field=models.CharField(default='#', max_length=20),
        ),
        migrations.AlterField(
            model_name='about',
            name='whatsapp',
            field=models.CharField(default='#', max_length=20),
        ),
    ]
